/* Generated By:JavaCC: Do not edit this line. ssc5906JMCConstants.java */
package br.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ssc5906JMCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int ssc5906JavaMC = 14;
  /** RegularExpression Id. */
  int STATES = 15;
  /** RegularExpression Id. */
  int PROPERTIES = 16;
  /** RegularExpression Id. */
  int DEFINE = 17;
  /** RegularExpression Id. */
  int VERIFYING = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int LBRACKET = 20;
  /** RegularExpression Id. */
  int RBRACKET = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int Lparentheses = 25;
  /** RegularExpression Id. */
  int Rparentheses = 26;
  /** RegularExpression Id. */
  int RECEIVE = 27;
  /** RegularExpression Id. */
  int IDENTIFIER = 28;
  /** RegularExpression Id. */
  int LETTER = 29;
  /** RegularExpression Id. */
  int DIGIT = 30;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 31;
  /** RegularExpression Id. */
  int INVALID_CONST = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"begin\"",
    "\"end\"",
    "\"ssc5906JavaMC\"",
    "\"states\"",
    "\"properties\"",
    "\"define\"",
    "\"verifying\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\":=\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
